# Single-node rustkube test cluster "tcluster3" — generated by deploy/new-tcluster.sh.
# Edit that script (or the shared template) rather than this file; re-running the
# script regenerates it and reuses this cluster's IP, VMID and PKI.

include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "git::ssh://git@github.com/glennswest/terraform-modules.git//modules/proxmox-fedora-vm?ref=v0.3.0"
}

locals {
  name          = "tcluster3"
  ip            = "192.168.8.63"
  vm_id         = 2007
  mac           = "BC:24:11:08:01:3F"
  cluster_token = "tcluster3-etcd"
  ssh_key       = trimspace(file(pathexpand("~/.ssh/id_rsa.pub")))
  pki           = "${get_terragrunt_dir()}/pki"

}

inputs = {
  dns_zone_id        = "9bed60c8-1664-4183-88f9-a1a21b927edc" # g8.lo
  ci_ssh_public_keys = [local.ssh_key]
  tags               = ["terraform", "fedora", "rustkube", "tcluster"]

  vm_datastore      = "test-lvm-thin"
  snippet_datastore = "terraform-snippets"

  vms = {
    (local.name) = {
      vm_id     = local.vm_id
      mac       = local.mac
      ip        = local.ip
      cores     = 2
      memory    = 2048
      disk_size = 20
      user_data = templatefile("${get_terragrunt_dir()}/../templates/tcluster-user-data.yaml.tftpl", {
        hostname         = local.name
        fqdn             = "${local.name}.g8.lo"
        ci_user          = "fedora"
        ssh_keys         = [local.ssh_key]
        node_ip          = local.ip
        cluster_token    = local.cluster_token
        with_node        = false
        node_token       = ""
        ca_crt        = file("${local.pki}/ca.crt")
        ca_key        = file("${local.pki}/ca.key")
        sa_key        = file("${local.pki}/sa.key")
        sa_pub        = file("${local.pki}/sa.pub")
        apiserver_crt = file("${local.pki}/apiserver.crt")
        apiserver_key = file("${local.pki}/apiserver.key")
        cm_crt        = file("${local.pki}/controller-manager.crt")
        cm_key        = file("${local.pki}/controller-manager.key")
        sched_crt     = file("${local.pki}/scheduler.crt")
        sched_key     = file("${local.pki}/scheduler.key")
        admin_crt     = file("${local.pki}/admin.crt")
        admin_key     = file("${local.pki}/admin.key")
      })
    }
  }
}
