# Unit: rustkube cluster — 3 master-nodes + 3 workers on g8.lo
#
# OpenShift-style compact cluster:
#   * master1/2/3 (.51/.52/.53) each run a fastetcd member (3-node Raft) AND the
#     Kubernetes control plane (apiserver + controller-manager + scheduler) AND
#     the node components (kubelet + kube-proxy) — schedulable master-nodes.
#   * worker1/2/3 (.54/.55/.56) run only the node components and join master1's
#     apiserver.
# Runtime is CRI-O (the OpenShift runtime); Cilium (CNI) is deployed cluster-wide
# once from the primary master (master1) by bootstrap-cilium, which is what takes
# nodes to Ready.
#
# Uses the shared, versioned proxmox-fedora-vm module (pinned ?ref). Disks →
# test-lvm-thin, cloud-init snippets → terraform-snippets (token ACL scope).

include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "git::ssh://git@github.com/glennswest/terraform-modules.git//modules/proxmox-fedora-vm?ref=v0.3.0"
}

locals {
  # No version pins. cloud-init installs the LATEST fastetcd and rustkube
  # releases at boot (install-latest-rpm resolves the newest GitHub release),
  # so the build pipeline drives what runs — user_data never carries a version
  # (a changed user_data forces a full VM replace). Released artifacts only; no
  # build on the node. Each master runs a member of the 3-node Raft cluster;
  # TLS off (plaintext) for first bring-up.
  cluster_token = "kube-etcd"
  ssh_key       = trimspace(file(pathexpand("~/.ssh/id_rsa.pub")))

  # Control-plane PKI (generated by deploy/gen-pki.sh; gitignored). Injected via
  # cloud-init so every apiserver serves TLS with a CA-signed cert and the
  # components authenticate with client certs. Run gen-pki.sh before apply.
  pki = "${get_terragrunt_dir()}/pki"

  # Fixed MAC -> reserved IP (outside the g8 DHCP pool .100-.200). vm_ids
  # allocated via deploy/terragrunt/free-vmid.sh (range 2000-2100). pod_cidr is a
  # /24 per node carved from the 10.244.0.0/16 cluster pod network.
  #
  # masters: schedulable master-nodes (control plane + fastetcd + kubelet).
  masters = {
    master1 = { vm_id = 2000, mac = "BC:24:11:08:00:51", ip = "192.168.8.51", pod_cidr = "10.244.0.0/24" }
    master2 = { vm_id = 2001, mac = "BC:24:11:08:00:52", ip = "192.168.8.52", pod_cidr = "10.244.1.0/24" }
    master3 = { vm_id = 2002, mac = "BC:24:11:08:00:53", ip = "192.168.8.53", pod_cidr = "10.244.2.0/24" }
  }
  # workers: kubelet + kube-proxy only, joining master1's apiserver.
  workers = {
    worker1 = { vm_id = 2020, mac = "BC:24:11:08:00:54", ip = "192.168.8.54", pod_cidr = "10.244.3.0/24" }
    worker2 = { vm_id = 2021, mac = "BC:24:11:08:00:55", ip = "192.168.8.55", pod_cidr = "10.244.4.0/24" }
    worker3 = { vm_id = 2022, mac = "BC:24:11:08:00:56", ip = "192.168.8.56", pod_cidr = "10.244.5.0/24" }
  }

  # fastetcd/apiserver topology derives from the masters only.
  initial_cluster = join(",", [for k, v in local.masters : "${k}=http://${v.ip}:2380"])
  # kube-apiserver --etcd-servers: every member's client URL.
  etcd_servers = join(",", [for k, v in local.masters : "http://${v.ip}:2379"])
  # workers reach the control plane at master1 (no LB/VIP yet — its serving cert
  # carries IP:192.168.8.51 as a SAN).
  worker_apiserver = "https://${local.masters["master1"].ip}:6443"
}

inputs = {
  dns_zone_id        = "9bed60c8-1664-4183-88f9-a1a21b927edc" # g8.lo
  ci_ssh_public_keys = [local.ssh_key]
  tags               = ["terraform", "fedora", "rustkube", "master"]

  # Match the terraform-svc token's ACL scope (test-lvm-thin is lvmthin →
  # disks only; snippets must live on the terraform-snippets dir storage).
  vm_datastore      = "test-lvm-thin"
  snippet_datastore = "terraform-snippets"

  vms = merge(
    # master-nodes: control plane + fastetcd + kubelet
    {
      for k, v in local.masters : k => {
        vm_id     = v.vm_id
        mac       = v.mac
        ip        = v.ip
        cores     = 4
        memory    = 4096
        disk_size = 40
        user_data = templatefile("${get_terragrunt_dir()}/templates/master-user-data.yaml.tftpl", {
          hostname         = k
          fqdn             = "${k}.g8.lo"
          ci_user          = "fedora"
          ssh_keys         = [local.ssh_key]
          node_ip          = v.ip
          pod_cidr         = v.pod_cidr
          initial_cluster  = local.initial_cluster
          cluster_token    = local.cluster_token
          etcd_servers     = local.etcd_servers
          cluster_state    = (get_env("RK_REPLACE_MASTER", "") == k) ? "existing" : "new"
          # master1 is the primary: it deploys Cilium (CNI) cluster-wide once.
          primary = (k == "master1")
          # PKI material, injected via cloud-init write_files.
          ca_crt        = file("${local.pki}/ca.crt")
          ca_key        = file("${local.pki}/ca.key")
          sa_key        = file("${local.pki}/sa.key")
          sa_pub        = file("${local.pki}/sa.pub")
          apiserver_crt = file("${local.pki}/apiserver-${k}.crt")
          apiserver_key = file("${local.pki}/apiserver-${k}.key")
          cm_crt        = file("${local.pki}/controller-manager.crt")
          cm_key        = file("${local.pki}/controller-manager.key")
          sched_crt     = file("${local.pki}/scheduler.crt")
          sched_key     = file("${local.pki}/scheduler.key")
          admin_crt     = file("${local.pki}/admin.crt")
          admin_key     = file("${local.pki}/admin.key")
          # Node identity: this master's SA-signed kubelet token.
          node_token = trimspace(file("${local.pki}/tokens/${k}"))
        })
      }
    },
    # workers: kubelet + kube-proxy only
    {
      for k, v in local.workers : k => {
        vm_id     = v.vm_id
        mac       = v.mac
        ip        = v.ip
        cores     = 4
        memory    = 4096
        disk_size = 40
        user_data = templatefile("${get_terragrunt_dir()}/templates/worker-user-data.yaml.tftpl", {
          hostname      = k
          fqdn          = "${k}.g8.lo"
          ci_user       = "fedora"
          ssh_keys      = [local.ssh_key]
          pod_cidr      = v.pod_cidr
          apiserver_url = local.worker_apiserver
          ca_crt        = file("${local.pki}/ca.crt")
          node_token    = trimspace(file("${local.pki}/tokens/${k}"))
        })
      }
    },
  )
}
